_wandb:
    value:
        cli_version: 0.28.0
        e:
            pfunenob7y3wqc9d5z1jq70wesnjkyz9:
                args:
                    - --slack_smoke_test
                codePath: SWM_copy/training/dynamics_model_clip_full_finetune.py
                codePathLocal: dynamics_model_clip_full_finetune.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1967317549056"
                        used: "1388190289920"
                email: ashwinkr@sas.upenn.edu
                executable: /home/ashwink/Documents/swms/.venv/bin/python
                git:
                    commit: 8fd057882c3cffd89cc9f4ef529ab595f612d2f1
                    remote: https://github.com/ash-bot-5/SWM_copy.git
                gpu: NVIDIA GeForce RTX 3090 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 3090 Ti
                      uuid: GPU-7f656875-d5ea-3c22-f9b2-c71c8106db21
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 3090 Ti
                      uuid: GPU-1eb68860-7232-542b-e54b-4e17175bc661
                host: jupiter
                memory:
                    total: "67275243520"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.35
                program: /home/ashwink/Documents/swms/SWM_copy/training/dynamics_model_clip_full_finetune.py
                python: CPython 3.10.12
                root: /home/ashwink/Documents/swms/SWM_copy/training
                startedAt: "2026-07-16T00:40:57.195905Z"
                writerId: pfunenob7y3wqc9d5z1jq70wesnjkyz9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.28.0
            "6": 4.57.1
            "12": 0.28.0
            "13": linux-x86_64
